{% set name = "libdrs" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CDAT/libdrs/archive/v3.0.1.tar.gz
  sha256: d42ddac6a3503e9a27ade9b2a9cfd3771b2e845d18297bdf679414cb7a818a07

build:
  number: 0
  skip: True  # [win] 

requirements:
  build:
    - libnetcdf >=4.5
    - g2clib
    - clang_osx-64 [osx]
    - gfortran_osx-64 [osx]
    - gcc_linux-64 [linux]
    - gfortran_linux-64 [linux]
  run:
    - libnetcdf >=4.5
    - g2clib
    - clang_osx-64 [osx]
    - libgcc [linux]

test:
  commands:
    - test -f $PREFIX/lib/libdrs.a 

about:
  home:  http://uvcdat.llnl.gov
  license: CCLRC
  summary: 'Data Retrieval and Storage DRS software C library'
  description: |            
    libdrs is suitable for the data generated and used in climate model research. 
    It is oriented toward use with models generating very large datasets on 
    supercomputers, as well as with graphics workstations used for analysis and 
    display of smaller subsets of data. 
  dev_url: http://github.com/UV-CDAT/libdrs

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
