{% set name = "libdrs" %}
{% set version = "3.1.2" %}
{% set build = 11 %}

# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}

{% if mpi == 'nompi' %}
# prioritize nompi variant
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CDAT/libdrs/archive/v{{ version }}.tar.gz
  sha256: 90e10191116a78228739276078a0ddcf0d6458516f192e9e79fecb2beeceb3fa

build:
  number: {{ build }}
  skip: True  # [win]

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `libdrs * mpi_mpich_*` for mpich
  # `libdrs * mpi_*` for any mpi
  # `libdrs * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"

requirements:
  build:
    - {{ compiler('c') }}         # need gcc7 to link library
    - {{ compiler('fortran') }}   # (_gmalloc_fortran) issue without gfortran7
  host:
    - libnetcdf
    - libnetcdf * {{ mpi_prefix }}_*
    - g2clib
  run:
    - libnetcdf * {{ mpi_prefix }}_*
    - g2clib

test:
  commands:
    - test -f $PREFIX/lib/libdrs.a

about:
  home:  http://cdat.llnl.gov
  summary: 'Data Retrieval and Storage DRS software Fortran library'
  license: BSD
  license_file: bsd-3-clause.txt
  description: |
    libdrs is suitable for the data generated and used in climate model research.
    It is oriented toward use with models generating very large datasets on
    supercomputers, as well as with graphics workstations used for analysis and
    display of smaller subsets of data.
  dev_url: http://github.com/CDAT/libdrs

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - downiec
    - muryanto1
    - jasonb5
    - xylar
