{% set name = "libdrs" %}
{% set version = "2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UV-CDAT/libdrs/archive/v2.10.tar.gz
  sha256: c6f2e1698187eeb04290bb4dd4e975127bf17a73d8d66e97a3f6f982422e660e  

build:
  number: 1
  skip: True  # [win] 

requirements:
  build:
    - libnetcdf 4.4.*
    - g2clib
    - gcc
  run:
    - libnetcdf 4.4.*
    - g2clib
    - libgcc

test:
  commands:
    - test -f $PREFIX/lib/libdrs.a 

about:
  home:  http://uvcdat.llnl.gov
  license: CCLRC
  summary: 'Data Retrieval and Storage DRS software C library'
  description: |            
    libdrs is suitable for the data generated and used in climate model research. 
    It is oriented toward use with models generating very large datasets on 
    supercomputers, as well as with graphics workstations used for analysis and 
    display of smaller subsets of data. 
  dev_url: http://github.com/UV-CDAT/libdrs

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
